services:
  - type: web
    name: sq-launchpad-backend
    env: python
    buildCommand: pip install -r app/launchpad/requirements.txt
    startCommand: cd app/launchpad && gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --threads 4 --log-level info main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        generateValue: true

